# Generated by Django 5.2.12 on 2026-06-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='notice_period_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
