# Generated by Django 5.2.12 on 2026-09-21 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_property_notice_period_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='price_per_night',
            new_name='default_price_per_night',
        ),
        migrations.AddField(
            model_name='property',
            name='default_min_nights',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='PropertyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], max_length=6)),
                ('min_nights', models.PositiveIntegerField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='bookings.property')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('property', 'date'), name='unique_property_availability_date')],
            },
        ),
    ]
